version: "2.0"

services:
  app:
    # image: USERNAME/IMAGE:TAG
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server/src/prisma:/data
      - ./server/src/cache:/cache
      - ./music:/music
    ports:
      - 4000:4000
