name: BUILD BASE IMAGE

on:
  push:
    branches:
      - main
    paths:
      - 'server/DockerfileBase'
      - 'server/src/package.json'
      - 'server/src/package-lock.json'
      - 'server/src/client/package.json'
      - 'server/src/client/package-lock.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v24
        with:
          context: ./server
          file: ./server/DockerfileBase
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: baealex/beato-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
