name: BUILD IMAGE

on:
  workflow_run:
    workflows: ["BUILD BASE IMAGE", "DEPLOY CLIENT"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: baealex/beato:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
