name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm i
      working-directory: server/src
    
    - name: Lint (Server)
      run: npm run lint
      working-directory: server/src
    
    - name: Test (Server)
      run: npm run test
      working-directory: server/src
    
    - name: Build (Server)
      run: npm run build
      working-directory: server/src
    
    - name: Lint (Client)
      run: npm run lint
      working-directory: server/src/client/src

    - name: Test (Client)
      run: npm run test
      working-directory: server/src/client/src

    - name: Build (Client)
      run: npm run build
      working-directory: server/src/client/src
